#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the dayOfProgrammer function below.
def dayOfProgrammer(year):
    if year==1918:
        return "26.09.1918"
    elif ((year%4 ==0) and year<1918) or ((year%400 ==0) or(year%4 ==0 and year%100 !=0) and (year >1918)):
        a = str(256-(31+29+31+30+31+30+31+31))
        b= (a+".09."+str(year))
    else:
        c=  str(256-(31+28+31+30+31+30+31+31))
        b = (c+".09."+str(year))

    return b
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
