#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    
    count=dict((i,ar.count(i))for i in ar)
    # ount = dict((i, ar.count(i)) for i in ar)
    sums = 0 
    for i in count.values():
        sums += i//2
    return sums

    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
